### ISSUE TITLE
executor failed running [/bin/sh -c pip3 install -r requirements.req]

### ISSUE THREAD

**Issue by Dirie** [aminelemaizi/micro-cluster-lab#3]
Hi,
It is a great project for beginners!
I have been dealing with this issue since this afternoon, could you please fix it. It occurs during docker build. Further, I totally new to spark on docker containers and got little experience in spark and hadoop.

`failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c pip3 install -r requirements.req]: runc did not terminate sucessfully.`

**Comment by xxarles** [comment]
In case anyone else faces this, It can be solved by updating pip before the install requirements line on the Dockerfile. I created a pull request that solver it
